---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: apparmor
  state_top:
    base:
      '*':
        - apparmor

platforms:
  - name: ubuntu-xenial
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - apparmor
        apparmor.sls:
          apparmor:
            complain:
              - usr.sbin.rsyslog
            enforce:
              - usr.sbin.nginx
              - usr.sbin.php7.0-fpm
              - usr.sbin.mysql
            disable:
              - usr.bin.ssh
            include:
              usr.sbin.php7.0-fpm: 
                - wordpress 

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE