sudo: required


language: ruby

services:
  - docker

before_install:
  - docker pull saltstack/ubuntu-14.04
  - pip install -r requirements.txt

script: 
  - mount securityfs -t securityfs /sys/kernel/security
  - bundle exec kitchen verify